### ISSUE TITLE
Using persistent data structure

### ISSUE THREAD

**Issue by NetanelBasal** [planttheidea/crio#3]
Is your library using a persistent data structure like immutable js for example?

**Comment by planttheidea** [comment]
Short answer: yes, for the most part.

crio aggressively tries to reuse objects whenever possible to keep memory allocation low, which is the foundation of a persistent data structure system. Example:

``` javascript
const crioArray = crio([{foo: 'bar'}]);
const addedCrioArray = crioArray.push({foo: 'baz'});

console.log(crioArray[0] === addedCrioArray[0]); // true

const mappedCrioArray = addedCrioArray.map((item) => {
    return item.set('foo', 'bar');
});

console.log(crioArray[0] === mappedCrioArray[0]); // true (same value === same object)

const filteredCrioArray = mappedCrioArray.filter((item, index) => {
    return index === 0;
});

console.log(crioArray[0] === filteredCrioArray[0]); // true

const concattedArray = crioArray.concat([{foo: 'baz'}]);

console.log(crioArray[0] === concattedArray[0]); // true
```

That said, there are inevitably some trade-offs that come with making objects truly immutable. crio makes all properties readonly on its object and uses Object.freeze on the object itself, which means it is truly unable to be changed. When I was using immutable.js, the objects were not actually immutable, rather they just buried the object values so deeply in the instance that it would have been extraordinarily difficult to change them. The benefit there is it allows more flexibility to reuse the object values; for example, I cannot reuse the object when converting it back to vanilla JS because of crio's immutable nature, I can only copy:

``` javascript
console.log(crioArray.thaw() === crioArray.thaw()); // false
```

Hope this answers the question, but I'll leave it open in case you have a follow-up.

**Comment by NetanelBasal** [comment]
Thanks, I will give this a try 👍
